# A list of packages to install globally. See commented examples below for
# usage; the 'release' is optional, and defaults to '@stable'.
composer_global_packages:
  # - { name: 'phpunit/phpunit', release: '4.7.x' }
  # - { name: 'phpunit/phpunit', release: '@stable' }
  - { name: 'hirak/prestissimo', release: '^0.3' }
